baseurl      = "https://sajadkarim.github.io/blog/"
title        = "Sajad Karim"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
publishDir = "docs"
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
IsMultilingual = true
#canonifyURLs = true

[params]
IsMultilingual = true
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  #homeSubtitle = "Everybody makes mistakes. Never regret them, correct them. There’s no such thing as a perfect world or perfect life. ― His Highness the Aga Khan IV"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]	

  EnableThemeToggle = true
  defaultTheme = "dark"


 
[params.footer]
  copyright = true
  #author = true
  trademark = "2024"
  topText = ["Powered by <a href='http://gohugo.io'>Hugo</a> (theme by <a href='https://github.com/rhazdon'>Djordje Atlialp</a>)"]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"


[[params.social]]
  name = "linkedin"
  url = "https://de.linkedin.com/in/sajadkarim"
[[params.social]]
  name = "github"
  url = "https://github.com/SajadKarim"
[[params.social]]
  name = "matrix"
  url = "@sajad.karim:matrix.org"
[[params.social]]
  name = "discord"
  url = "@sajad.karim"
[[params.social]]
  name = "X"
  url = "https://twitter.com/sajadkarim"
[[params.social]]
  name = "researchgate"
  url = "#"
[[params.social]]
  name = "orcid"
  url = "#"
[[params.social]]
  name = "googlescholar"
  url = "https://www.researchgate.net/profile/Sajad_Karim"
[[params.social]]
  name = "case"
  url = "https://www.dbse.ovgu.de/en/Staff/Sajad+Karim.html"
[[params.social]]
  name = "email"
  url = "mailto:sajad.karim<at>gmail<dot>com"

defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = false

[languages]
  [languages.de]
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'de'    
    title = "Sayad Karim"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    readOtherPosts = "Read other posts"
    homeSubtitle = "Jeder macht Fehler. Bereue sie nie, korrigiere sie. Es gibt weder eine perfekte Welt noch ein perfektes Leben. ― His Highness the Aga Khan IV"
    contentDir = "content/de"
    [languages.de.params.logo]
      #logoText = "sajad.karim@abdul.rahim:~$"
      logoText = "lila@saj:~$"
      logoHomeLink = ""
      logoCursorColor = "#074ada"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[languages.de.menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about"
  [[languages.de.menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "#"
  [[languages.de.menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "#"    
  [[languages.de.menu.main]]
    identifier = "publications"
    name       = "Publications"
    url        = "#"

  [languages.en]
    languageCode = 'en-EN'
    languageDirection = 'ltr'
    languageName = 'en'
    title = "Sajad Karim"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    homeSubtitle = "Everybody makes mistakes. Never regret them, correct them. There’s no such thing as a perfect world or perfect life. ― His Highness the Aga Khan IV"
	contentDir = "content/en"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      #logoText = "sajad.karim@abdul.rahim:~$"
      logoText = "lila@saj:~$"
      logoHomeLink = ""
      logoCursorColor = "#074ada"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[languages.en.menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[languages.en.menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[languages.en.menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "#"    
  [[languages.en.menu.main]]
    identifier = "publications"
    name       = "Publications"
    url        = "#"

  [languages.bru]
    languageCode = 'bru'
    languageDirection = 'ltr'
    languageName = 'bru'    
    title = "Shookrullah Baig"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    homeSubtitle = "Jay me datlas bābo kay shākar māma mo shookro ba!"
    readOtherPosts = "Read other posts"
    flag = "/images/bru.svg"
contentDir = "content/bru"
    [languages.bru.params.logo]
      #logoText = "sajad.karim@abdul.rahim:~$"
      logoText = "lila@saj:~$"
      logoHomeLink = ""
      logoCursorColor = "#074ada"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
    [[languages.bru.menu.main]]
      identifier = "about"
      name       = "About"
      url        = "/about"

[markup.goldmark.renderHooks.image]
enableDefault = true

[markup.goldmark.renderHooks.link]
enableDefault = true

[[module.mounts]]
source = 'assets'
target = 'assets'

[[module.mounts]]
source = 'static'
target = 'assets'
